<a href="https://colab.research.google.com/github/cchio74/forgemaster/blob/master/Lab02_numpy_bj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [1]:
import numpy as np

In [2]:
data1=[1,2,3,4,5]

In [3]:
type(data1)

list

In [4]:
len(data1)

5

In [5]:
type(data1[0])

int

In [7]:
data2=[1,2,3,3.5,4]

In [8]:
type(data2[0])

int

In [10]:
a1=np.array(data1)

In [11]:
a1

array([1, 2, 3, 4, 5])

In [12]:
a2=np.array(data2)

In [13]:
a2

array([1. , 2. , 3. , 3.5, 4. ])

In [14]:
a1.shape

(5,)

In [15]:
len(a1)

5

##shape는 array에서만 사용가능

In [16]:
a1.size

5

In [17]:
a1.ndim

1

In [19]:
a2.dtype

dtype('float64')

In [21]:
a2.ndim

1

In [24]:
a4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [25]:
a4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
a4.shape

(4, 3)

In [27]:
a4.ndim

2

In [28]:
a4.size

12

In [29]:
a4.dtype

dtype('int64')

In [34]:
np.zeros((2,3,3,1))

array([[[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]]])

In [37]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.arange(-10,10,1.5)

array([-10. ,  -8.5,  -7. ,  -5.5,  -4. ,  -2.5,  -1. ,   0.5,   2. ,
         3.5,   5. ,   6.5,   8. ,   9.5])

In [43]:
np.arange(9).shape

(9,)

In [44]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
np.zeros((4,4)).reshape(8,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
a1=np.arange(1,7).reshape(2,3)

In [57]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a2=np.arange(10,16).reshape(2,3)

In [61]:
a2

array([[10, 11, 12],
       [13, 14, 15]])

In [62]:
a1+a2

array([[11, 13, 15],
       [17, 19, 21]])

In [63]:
a1-a2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [64]:
a1*a2

array([[10, 22, 36],
       [52, 70, 90]])

In [65]:
a1/a2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [67]:
a3=np.array([10,11,12])

In [68]:
a3

array([10, 11, 12])

In [70]:
a1.shape, a3.shape

((2, 3), (3,))

In [71]:
a1+a3

array([[11, 13, 15],
       [14, 16, 18]])

In [72]:
a1*10

array([[10, 20, 30],
       [40, 50, 60]])

In [73]:
a1**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [74]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [75]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a1[1,1]

5

In [77]:
a1[0,0]

1

In [78]:
a1[0][0]

1

In [79]:
a1[0,0]

1

In [80]:
a1[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a1=np.arange(10)

In [83]:
a1[1:8:2]

array([1, 3, 5, 7])

In [84]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [87]:
name=np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])

In [88]:
name.shape

(8,)

In [89]:
name.ndim

1

In [90]:
name.size

8

In [91]:
name.dtype

dtype('<U7')

In [93]:
mask=name=='Beomwoo'

In [94]:
mask

array([ True,  True, False, False, False,  True, False,  True])

In [96]:
data=np.random.randn(8,4)

In [97]:
data

array([[-0.36040504, -0.63032658, -0.07946879,  0.21683939],
       [ 1.67703999,  0.97075763,  0.93662959, -0.73291278],
       [ 1.08146103, -0.44762411,  0.24826854, -0.74706979],
       [-0.19736528, -2.43115522, -0.90801511, -0.63592227],
       [ 1.12306874,  0.35047805, -0.83052813,  0.62553289],
       [ 0.05718654,  0.33496228, -2.07455534, -1.01357105],
       [ 0.24659224,  0.14458486,  0.73354388, -0.60332124],
       [-0.1220529 ,  0.65384737,  0.86172074,  0.58163344]])

In [98]:
name

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [99]:
mask

array([ True,  True, False, False, False,  True, False,  True])

In [100]:
data[name=='Beomwoo']

array([[-0.36040504, -0.63032658, -0.07946879,  0.21683939],
       [ 1.67703999,  0.97075763,  0.93662959, -0.73291278],
       [ 0.05718654,  0.33496228, -2.07455534, -1.01357105],
       [-0.1220529 ,  0.65384737,  0.86172074,  0.58163344]])

In [101]:
a1=np.random.randn(5,3)

In [103]:
a1=np.random.randn(5,3)

In [104]:
a1

array([[ 0.01500255,  0.72788909,  1.64971598],
       [-0.15787013, -1.97246888, -0.14662159],
       [ 0.91947225,  1.53844515, -1.11352796],
       [-0.7828641 , -1.64684227, -0.04947244],
       [ 0.0165523 , -1.33283792, -1.14533927]])

In [105]:
np.sqrt(a1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[0.12248491, 0.85316416, 1.2844127 ],
       [       nan,        nan,        nan],
       [0.95889116, 1.24034074,        nan],
       [       nan,        nan,        nan],
       [0.12865575,        nan,        nan]])

In [107]:
np.square(a1)

array([[2.25076590e-04, 5.29822527e-01, 2.72156282e+00],
       [2.49229784e-02, 3.89063349e+00, 2.14978918e-02],
       [8.45429223e-01, 2.36681347e+00, 1.23994453e+00],
       [6.12876192e-01, 2.71208946e+00, 2.44752213e-03],
       [2.73978740e-04, 1.77645691e+00, 1.31180205e+00]])

In [108]:
a1**2

array([[2.25076590e-04, 5.29822527e-01, 2.72156282e+00],
       [2.49229784e-02, 3.89063349e+00, 2.14978918e-02],
       [8.45429223e-01, 2.36681347e+00, 1.23994453e+00],
       [6.12876192e-01, 2.71208946e+00, 2.44752213e-03],
       [2.73978740e-04, 1.77645691e+00, 1.31180205e+00]])

In [109]:
np.log(a1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[-4.19953491, -0.31760659,  0.50060314],
       [        nan,         nan,         nan],
       [-0.08395541,  0.43077226,         nan],
       [        nan,         nan,         nan],
       [-4.10123002,         nan,         nan]])

In [110]:
np.sign(a1)

array([[ 1.,  1.,  1.],
       [-1., -1., -1.],
       [ 1.,  1., -1.],
       [-1., -1., -1.],
       [ 1., -1., -1.]])

In [111]:
np.ceil(a1)

array([[ 1.,  1.,  2.],
       [-0., -1., -0.],
       [ 1.,  2., -1.],
       [-0., -1., -0.],
       [ 1., -1., -1.]])

In [112]:
np.isnan(np.sqrt(a1))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[False, False, False],
       [ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [113]:
a1/0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ inf,  inf,  inf],
       [-inf, -inf, -inf],
       [ inf,  inf, -inf],
       [-inf, -inf, -inf],
       [ inf, -inf, -inf]])

In [115]:
a1=np.arange(9).reshape(3,3)

In [116]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
a2=np.arange(6).reshape(3,2)

In [118]:
a2

array([[10, 11, 12],
       [13, 14, 15]])

In [121]:
np.matmul(a1,a2)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [122]:
a1@a2

array([[10, 13],
       [28, 40],
       [46, 67]])