<a href="https://colab.research.google.com/github/cchio74/forgemaster/blob/master/lab02_LHC_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#제 2장. Numpy (numerical python)
- numpy는 python을 통해 데이터를 분석할 때 기초 라이브러리로 사용된다.
- 벡터, 행렬을 계산하는데 매우 유용하다.
- 기본적으로 array(행렬)을 기초 단위로 한다.


##Array 표기

In [2]:
import numpy as np #앞으로 numpy를 np로 대체하겠다.

In [6]:
data1=[1,2,3,4,5]

In [7]:
type(data1)

list

In [8]:
len(data1)

5

In [9]:
type(data1[0]) #리스트 내부 하나의 요소에 대한 타입도 확인할 수 있다.

int

In [11]:
data2=[1,2,3,3.5,4]

In [14]:
type(data2[0])

int

In [28]:
ar1=np.array(data1)

In [29]:
ar1

array([1, 2, 3, 4, 5])

In [30]:
ar2=np.array(data2)

In [31]:
ar2

array([1. , 2. , 3. , 3.5, 4. ])

In [32]:
len(ar1)

5

In [33]:
ar1

array([1, 2, 3, 4, 5])

In [35]:
ar1. shape

(5,)

In [37]:
ar1. size

5

In [38]:
ar1. dtype

dtype('int64')

In [39]:
ar2.dtype

dtype('float64')

In [47]:
ar4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float64')

In [48]:
ar4

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [49]:
ar4.shape

(4, 3)

In [50]:
ar4.ndim

2

In [51]:
ar4.size

12

In [52]:
ar4.dtype

dtype('float64')

In [56]:
np.zeros((2,3))  #0이 2*3짜리 행렬이 만들어짐 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
range(10)

range(0, 10)

In [65]:
for i in range(10):
    print(i)
    #arrey에서 arange와 비슷함


0
1
2
3
4
5
6
7
8
9


In [67]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(-10,10,1.5) #첫숫자는 시작, 두번째 숫자는 최대값, 마지막 숫자는 간격 

array([-10. ,  -8.5,  -7. ,  -5.5,  -4. ,  -2.5,  -1. ,   0.5,   2. ,
         3.5,   5. ,   6.5,   8. ,   9.5])

In [71]:
np.arange(9). shape

(9,)

In [72]:
np.arange(9).reshape((3,3)) #(0,1,2,3,4,5,6,7,8)을 3*3 으로 바꿈

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.zeros((3,4)).reshape(4,3) #3*4를 4*3으로 바꿈

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.zeros((3,4)).reshape(2,-1) #3*4를 2*x로 바꿈

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [83]:
np.zeros((3,4)).reshape(-1) #3*4를 쭉 나열함

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
np.zeros((3,4)).reshape(-1).shape

(12,)

## Array의 연산

In [90]:
a1=np.arange(1,7).reshape(2,3)

In [91]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
a2=np.arange(10,16).reshape(2,3)

In [93]:
a2

array([[10, 11, 12],
       [13, 14, 15]])

In [94]:
a1+a2

array([[11, 13, 15],
       [17, 19, 21]])

In [95]:
a1-a2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [96]:
a1*a2

array([[10, 22, 36],
       [52, 70, 90]])

In [97]:
a1/a2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

사칙연산중 곱, 나누기는 우리가 일반적으로 알고 있는 행렬 곱과 나누기가 아니고, 동일한 행과 열에 있는 숫자 끼리 사칙연산을 함

In [98]:
a3=np.array([10,11,13])

In [99]:
a1.shape #2차원

(2, 3)

In [100]:
a3.shape #1차원

(3,)

In [101]:
a1+a3

array([[11, 13, 16],
       [14, 16, 19]])

In [102]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a3

array([10, 11, 13])

a1은 2*3인 2차원이고 a3는 1차원이다. 사이즈가 다르기 때문에 브로드캐스트 기능을 사용해서 사이즈가 작은 것을 큰 것에 마춰서 계산 가능하게 함.

In [104]:
[1,2,3]*3 #리스트의 곱

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [106]:
a3*10 #우리가 알고 있는 스칼라 곱은 브로드캐스트 기능을 적용되어 계산함.

array([100, 110, 130])

In [108]:
a3**2

array([100, 121, 169])

##Array 인덱싱

In [110]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [111]:
list(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [112]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [113]:
l[0]

[1, 2, 3]

In [114]:
l[0][0]

1

list에서 [1,1]로 인덱싱할 수 없다.
그러나 array에서는 [1,1]의 형태로 인덱싱할 수 있다.

In [115]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
a1[0,0]

1

In [117]:
a1[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
a1[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [119]:
a1[:2,:2]

array([[1, 2],
       [4, 5]])

In [120]:
a1[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
a1[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
a1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
a1[1:5]

array([1, 2, 3, 4])

In [126]:
a1[1:5:2] #0~5사이만 부른다, 이때 한(2-1)칸 띄우고 불러라

array([1, 3])

In [127]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
a1[::-1] #0~끝까지 뒤로 한칸씩 불러라

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [130]:
a1[1::2] #1~끝까지 한(2-1)칸 띄우고 불러라

array([1, 3, 5, 7, 9])

##Array boolean 인덱싱

In [131]:
name=np.array(['beomwoo','beomwoo','Kim','Joan','Lee','beomwoo','Park','beomwoo'])

In [132]:
name

array(['beomwoo', 'beomwoo', 'Kim', 'Joan', 'Lee', 'beomwoo', 'Park',
       'beomwoo'], dtype='<U7')

In [134]:
name.shape

(8,)

In [136]:
name.ndim

1

In [137]:
name.size

8

In [138]:
name.dtype

dtype('<U7')

In [143]:
name[:]

array(['beomwoo', 'beomwoo', 'Kim', 'Joan', 'Lee', 'beomwoo', 'Park',
       'beomwoo'], dtype='<U7')

In [145]:
mask=name=='beomwoo' #'beomwoo'인 곳은 true 아닌 곳은 false

In [146]:
mask

array([ True,  True, False, False, False,  True, False,  True])

In [147]:
name[name=='beomwoo'] #'beomwoo'만 뽑아냄


array(['beomwoo', 'beomwoo', 'beomwoo', 'beomwoo'], dtype='<U7')

In [150]:
data=np.random.randn(8,4)

In [151]:
data

array([[ 1.35577442,  0.28875382, -1.03944544, -1.90755721],
       [-0.14649905, -0.58987789, -0.15273824,  1.28001879],
       [-0.09422151,  1.24794839, -0.70380046,  0.75146749],
       [-0.70986038, -0.34301511, -0.28070375, -0.17282571],
       [ 0.24698939,  0.94131909,  0.01471369,  0.04125424],
       [-1.28996738,  0.15375325,  0.67317943, -0.18973155],
       [ 0.12353082,  1.27253863, -0.89211781,  0.53427712],
       [-0.85210681, -0.29428364, -1.4399787 ,  0.9432086 ]])

In [152]:
name

array(['beomwoo', 'beomwoo', 'Kim', 'Joan', 'Lee', 'beomwoo', 'Park',
       'beomwoo'], dtype='<U7')

In [153]:
mask

array([ True,  True, False, False, False,  True, False,  True])

In [155]:
data[name=='beomwoo']

array([[ 1.35577442,  0.28875382, -1.03944544, -1.90755721],
       [-0.14649905, -0.58987789, -0.15273824,  1.28001879],
       [-1.28996738,  0.15375325,  0.67317943, -0.18973155],
       [-0.85210681, -0.29428364, -1.4399787 ,  0.9432086 ]])

##Numpy 함수

In [156]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a1=np.random.randn(5,3)

In [158]:
a1

array([[-0.02251221, -0.75022233,  0.1458952 ],
       [-0.24501278,  0.14543966, -0.58104331],
       [ 1.18914249,  1.50871594,  0.23350747],
       [-1.56663386,  1.85019098, -0.91891051],
       [ 0.77515075, -0.18950515, -2.31974474]])

In [160]:
a1=np.random.randint(0,10,(5,3)) #최소, 최대, 사이즈 ->랜덤으로 5*3 array를 만든다.
print(a1)

[[4 9 9]
 [0 7 1]
 [5 7 9]
 [7 1 8]
 [7 3 2]]


In [161]:
a2=np.random.randn(5,3)

In [162]:
a2

array([[ 1.2707159 , -0.1255733 , -0.45139333],
       [ 0.66660005, -3.00184044,  0.47528477],
       [ 0.13426649, -0.41332314,  0.47971314],
       [ 1.64871329, -0.15564336, -0.55120122],
       [ 0.07980947,  1.11646712,  0.1278678 ]])

In [164]:
np.abs(a2)

array([[1.2707159 , 0.1255733 , 0.45139333],
       [0.66660005, 3.00184044, 0.47528477],
       [0.13426649, 0.41332314, 0.47971314],
       [1.64871329, 0.15564336, 0.55120122],
       [0.07980947, 1.11646712, 0.1278678 ]])

In [165]:
np.sqrt(a2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.12726035,        nan,        nan],
       [0.81645579,        nan, 0.689409  ],
       [0.36642391,        nan, 0.69261327],
       [1.28402231,        nan,        nan],
       [0.28250571, 1.05663008, 0.35758608]])

In [166]:
np.exp(a2)

array([[3.5634027 , 0.88199111, 0.63674034],
       [1.9476043 , 0.04969552, 1.60847218],
       [1.14369756, 0.66144851, 1.61561088],
       [5.20028425, 0.85586437, 0.57625718],
       [1.08308069, 3.05404555, 1.13640277]])

In [167]:
np.log(a2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[ 0.23958044,         nan,         nan],
       [-0.40556504,         nan, -0.74384113],
       [-2.00792876,         nan, -0.73456698],
       [ 0.49999516,         nan,         nan],
       [-2.52811305,  0.11016934, -2.05675833]])

In [168]:
np.sign(a2)

array([[ 1., -1., -1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [ 1., -1., -1.],
       [ 1.,  1.,  1.]])

In [170]:
np.ceil(a2)

array([[ 2., -0., -0.],
       [ 1., -3.,  1.],
       [ 1., -0.,  1.],
       [ 2., -0., -0.],
       [ 1.,  2.,  1.]])

In [172]:
np.floor(a2)

array([[ 1., -1., -1.],
       [ 0., -4.,  0.],
       [ 0., -1.,  0.],
       [ 1., -1., -1.],
       [ 0.,  1.,  0.]])

In [173]:
np.isnan(np.log(a2))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[False,  True,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True],
       [False, False, False]])

In [174]:
np.log(a2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[ 0.23958044,         nan,         nan],
       [-0.40556504,         nan, -0.74384113],
       [-2.00792876,         nan, -0.73456698],
       [ 0.49999516,         nan,         nan],
       [-2.52811305,  0.11016934, -2.05675833]])

In [179]:
np.isinf(a2/10)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [180]:
a2

array([[ 1.2707159 , -0.1255733 , -0.45139333],
       [ 0.66660005, -3.00184044,  0.47528477],
       [ 0.13426649, -0.41332314,  0.47971314],
       [ 1.64871329, -0.15564336, -0.55120122],
       [ 0.07980947,  1.11646712,  0.1278678 ]])

In [203]:
a1=np.arange(9).reshape(3,3)

In [204]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [205]:
a2=np.arange(6).reshape(3,2)

In [206]:
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [207]:
np.matmul(a1,a2)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [208]:
np.dot(a1,a2)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [209]:
a1@a2

array([[10, 13],
       [28, 40],
       [46, 67]])

In [210]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [211]:
np.min(a1)

0

In [212]:
np.max(a1)

8

In [214]:
np.min(a1,axis=0) #열 중 작은것

array([0, 1, 2])

In [215]:
np.min(a1,axis=1) #행 중 작은것

array([0, 3, 6])

In [216]:
np.cumsum(a1) #점차 하나씩 더 더한 값을 나열

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [218]:
np.cumsum(a1,axis=0)  #열방향으로 점차 하나씩 더 더한값을 나열

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [219]:
np.cumsum(a1,axis=1) #행방향으로 점차 하나씩 더 더한값을 나열

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])