<a href="https://colab.research.google.com/github/cchio74/forgemaster/blob/master/lab10_linear_regression_LHC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np


In [2]:
tf.__version__

'2.3.0'

##data

In [5]:
x_data=np.array([1,2,3,4,5],np.float32)
x_data.dtype

dtype('float32')

In [7]:
x_data

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
y_data=np.array([1,2,3,4,5],np.float32)
y_data

array([1., 2., 3., 4., 5.], dtype=float32)

In [9]:
x_data.shape

(5,)

##Linear regression

In [10]:
learning_rate=1e-2

In [47]:
# w, b를 정하면 됨. tensor flow의 variable 함수를 사용하면 됨.
w=tf.Variable([0],dtype='float32',name='weight')
b=tf.Variable([0],dtype='float32',name='bias')
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [16]:
b

<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [18]:
hypothesis=x_data*w+b
hypothesis

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [23]:
loss=tf.math.square(hypothesis-y_data) #np로 제곱하면 형변환됨. 
loss

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25.], dtype=float32)>

In [26]:
loss=tf.reduce_mean(tf.math.square(hypothesis-y_data)) #np로 쓰면 형변환됨
loss

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

In [35]:
with tf.GradientTape() as tape:   #편미분을 구하기 위해서
    hypothesis=x_data*w+b
    loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))

In [36]:
w_grad,b_grad=tape.gradient(loss,[w,b]) #타겟은 loss, 소스는 w,b

In [37]:
w_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-22.], dtype=float32)>

In [38]:
b_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-6.], dtype=float32)>

In [39]:
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [43]:
w-learning_rate*w_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.22], dtype=float32)>

In [44]:
b-learning_rate*b_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.06], dtype=float32)>

In [48]:
for i in range(10):
    with tf.GradientTape() as tape:
        hypothesis=x_data*w+b
        loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))
    
    w_grad,b_grad=tape.gradient(loss,[w,b])

    w.assign_sub(learning_rate*w_grad)
    b.assign_sub(learning_rate*b_grad)

    print('{} {}'.format(i,loss))

0 11.0
1 6.415200233459473
2 3.7433724403381348
3 2.1863298416137695
4 1.2789298295974731
5 0.7501095533370972
6 0.4419064521789551
7 0.2622687816619873
8 0.15755288302898407
9 0.09649773687124252


In [49]:
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.86870116], dtype=float32)>

In [50]:
b

<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.23139274], dtype=float32)>

In [51]:
y_data

array([1., 2., 3., 4., 5.], dtype=float32)

In [52]:
x_data*w+b

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.1000938, 1.9687951, 2.8374963, 3.7061973, 4.5748987],
      dtype=float32)>

In [53]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1)) #초기값이랑 learn rate가 디폴트로 다른게 들어있어서 우리가 했던거랑 차이가 있음. 그럼 hypothesis는???도 똑같은가?

In [54]:
model.compile(optimizer='SGD',loss='mse')

In [56]:
model.fit(x_data,y_data,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 28.2988
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 16.5038
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 9.6303
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 5.6246
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 3.2902
Epoch 6/10
1/1 [==============================] - 0s 1ms/step - loss: 1.9297
Epoch 7/10
1/1 [==============================] - 0s 992us/step - loss: 1.1369
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6747
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4053
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2483


In [58]:
model.get_weights()

[array([[0.7894048]], dtype=float32), array([0.37113947], dtype=float32)]

In [59]:
model.predict(x_data)

array([[1.1605443],
       [1.949949 ],
       [2.739354 ],
       [3.5287588],
       [4.3181634]], dtype=float32)