<a href="https://colab.research.google.com/github/cchio74/forgemaster/blob/master/lab10_linear_regression_BJ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.3.0'

# DATA

In [9]:
x_data=np.array([1,2,3,4,5],np.float32)
x_data.shape

(5,)

In [10]:
y_data=np.array([1,2,3,4,5],np.float32)
y_data.shape

(5,)

# Linear regression

In [11]:
learning_rate=1e-2 

In [73]:
w=tf.Variable([0],dtype='float32',name='weight')
b=tf.Variable([0],dtype='float32',name='bias')
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [13]:
b

<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [14]:
hypothesis=x_data*w+b

In [15]:
hypothesis

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [25]:
loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))
loss

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

In [37]:
with tf.GradientTape() as tape:
  hypothesis=x_data*w+b
  loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))


In [38]:
w_grad,b_grad=tape.gradient(loss,[w,b])

In [39]:
w_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-22.], dtype=float32)>

In [40]:
b_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-6.], dtype=float32)>

In [70]:
w=w-learning_rate*w_grad

In [71]:
b=b-learning_rate*b_grad

In [74]:
for i in range(10):
  with tf.GradientTape() as tape:
    hypothesis=x_data*w+b
    loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))
 
  w_grad,b_grad=tape.gradient(loss,[w,b])

  w.assign_sub(learning_rate*w_grad)
  b.assign_sub(learning_rate*b_grad)

  print('{} {}'.format(i,loss))



  

0 11.0
1 6.415200233459473
2 3.7433724403381348
3 2.1863298416137695
4 1.2789298295974731
5 0.7501095533370972
6 0.4419064521789551
7 0.2622687816619873
8 0.15755288302898407
9 0.09649773687124252


In [93]:
model=tf.keras.Sequential()

In [94]:
model.add(tf.keras.layers.Dense(1))

In [95]:
model.compile(optimizer='SGD',loss='mse')

In [105]:
model.fit(x_data,y_data,epochs=100,verbose=2)

Epoch 1/100
1/1 - 0s - loss: 1.4487e-05
Epoch 2/100
1/1 - 0s - loss: 1.4388e-05
Epoch 3/100
1/1 - 0s - loss: 1.4292e-05
Epoch 4/100
1/1 - 0s - loss: 1.4196e-05
Epoch 5/100
1/1 - 0s - loss: 1.4099e-05
Epoch 6/100
1/1 - 0s - loss: 1.4005e-05
Epoch 7/100
1/1 - 0s - loss: 1.3909e-05
Epoch 8/100
1/1 - 0s - loss: 1.3816e-05
Epoch 9/100
1/1 - 0s - loss: 1.3722e-05
Epoch 10/100
1/1 - 0s - loss: 1.3630e-05
Epoch 11/100
1/1 - 0s - loss: 1.3538e-05
Epoch 12/100
1/1 - 0s - loss: 1.3447e-05
Epoch 13/100
1/1 - 0s - loss: 1.3356e-05
Epoch 14/100
1/1 - 0s - loss: 1.3265e-05
Epoch 15/100
1/1 - 0s - loss: 1.3176e-05
Epoch 16/100
1/1 - 0s - loss: 1.3087e-05
Epoch 17/100
1/1 - 0s - loss: 1.2999e-05
Epoch 18/100
1/1 - 0s - loss: 1.2911e-05
Epoch 19/100
1/1 - 0s - loss: 1.2824e-05
Epoch 20/100
1/1 - 0s - loss: 1.2737e-05
Epoch 21/100
1/1 - 0s - loss: 1.2651e-05
Epoch 22/100
1/1 - 0s - loss: 1.2566e-05
Epoch 23/100
1/1 - 0s - loss: 1.2481e-05
Epoch 24/100
1/1 - 0s - loss: 1.2397e-05
Epoch 25/100
1/1 - 0s - l

In [102]:
model.get_weights()

[array([[0.9965329]], dtype=float32), array([0.0125172], dtype=float32)]

In [103]:
model.predict(x_data)

array([[1.0090501],
       [2.005583 ],
       [3.002116 ],
       [3.998649 ],
       [4.9951816]], dtype=float32)