<a href="https://colab.research.google.com/github/cchio74/forgemaster/blob/master/lab10_linear_regression_BJ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.4.0'

# DATA

In [3]:
x_data=np.array([1,2,3,4,5],np.float32)
x_data.shape

(5,)

In [4]:
y_data=np.array([1,2,3,4,5],np.float32)
y_data.shape

(5,)

# Linear regression

In [5]:
learning_rate=1e-2 

In [6]:
w=tf.Variable([0],dtype='float32',name='weight')
b=tf.Variable([0],dtype='float32',name='bias')
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [7]:
b

<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [8]:
hypothesis=x_data*w+b

In [9]:
hypothesis

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [10]:
loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))
loss

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

In [11]:
with tf.GradientTape() as tape:
  hypothesis=x_data*w+b
  loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))


In [12]:
w_grad,b_grad=tape.gradient(loss,[w,b])

In [13]:
w_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-22.], dtype=float32)>

In [14]:
b_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-6.], dtype=float32)>

In [15]:
w=w-learning_rate*w_grad

In [16]:
b=b-learning_rate*b_grad

In [17]:
for i in range(10):
  with tf.GradientTape() as tape:
    hypothesis=x_data*w+b
    loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))
 
  w_grad,b_grad=tape.gradient(loss,[w,b])

  w.assign_sub(learning_rate*w_grad)
  b.assign_sub(learning_rate*b_grad)

  print('{} {}'.format(i,loss))



  

AttributeError: ignored

In [ ]:
model=tf.keras.Sequential()

In [ ]:
model.add(tf.keras.layers.Dense(1))

In [ ]:
model.compile(optimizer='SGD',loss='mse')

In [ ]:
model.fit(x_data,y_data,epochs=100,verbose=2)

In [ ]:
model.get_weights()

In [ ]:
model.predict(x_data)

# subclassing

In [69]:
class Model(tf.keras.layers.Layer):
  def __init__(self):
    super(Model,self).__init__()

    self.w=self.add_weight(shape=(1,1),initializer='random_normal')
    self.b=self.add_weight(shape=(1,),initializer='zeros')

  def call(self,inputs):
    return inputs*self.w + self.b

In [70]:
loss=tf.keras.losses.MeanSquaredError()

In [71]:
def grad(model,inputs,targets):
  with tf.GradientTape() as tape:
    loss_value=loss(targets,model(inputs))
  
  return tape.gradient(loss_value,[model.w,model.b])


In [72]:
model=Model()

In [56]:
model.w

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.9492163]], dtype=float32)>

In [38]:
optimizer=tf.keras.optimizers.SGD()

In [73]:
for i in range(100):
  grads=grad(model,x_data,y_data)

  optimizer.apply_gradients(zip(grads,[model.w,model.b]))

  print('{} {}'.format(i,loss(y_data,model(x_data))))


0 6.886382102966309
1 4.018314838409424
2 2.3469111919403076
3 1.3728647232055664
4 0.8052032589912415
5 0.47436389327049255
6 0.28153225779533386
7 0.16912488639354706
8 0.10358551889657974
9 0.06535825878381729
10 0.043047692626714706
11 0.03001280501484871
12 0.02238333784043789
13 0.017904266715049744
14 0.015261271968483925
15 0.013688487000763416
16 0.012739583849906921
17 0.012154418043792248
18 0.011781523935496807
19 0.011532509699463844
20 0.01135584432631731
21 0.011221630498766899
22 0.011112334206700325
23 0.011017780750989914
24 0.01093200035393238
25 0.010851572267711163
26 0.010774454101920128
27 0.010699453763663769
28 0.010625921189785004
29 0.01055342610925436
30 0.010481755249202251
31 0.010410711169242859
32 0.010340305976569653
33 0.010270403698086739
34 0.01020101923495531
35 0.010132122784852982
36 0.01006370596587658
37 0.009995779022574425
38 0.009928295388817787
39 0.009861250407993793
40 0.009794690646231174
41 0.009728561155498028
42 0.00966288149356842
43 

In [74]:
model.w

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.94738436]], dtype=float32)>

In [75]:
model.b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.18995921], dtype=float32)>