<a href="https://colab.research.google.com/github/cchio74/forgemaster/blob/master/lab10_linear_regression_LHC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np


In [3]:
tf.__version__

'2.4.0'

##data

In [45]:
x_data=np.array([1,2,3,4,5],np.float32)
x_data.dtype

dtype('float32')

In [46]:
x_data

array([1., 2., 3., 4., 5.], dtype=float32)

In [47]:
y_data=np.array([1,2,3,4,5],np.float32)
y_data

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
x_data.shape

(5,)

##Linear regression

In [8]:
learning_rate=1e-2

In [9]:
# w, b를 정하면 됨. tensor flow의 variable 함수를 사용하면 됨.
w=tf.Variable([0],dtype='float32',name='weight')
b=tf.Variable([0],dtype='float32',name='bias')
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [10]:
b

<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [11]:
hypothesis=x_data*w+b
hypothesis

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [12]:
loss=tf.math.square(hypothesis-y_data) #np로 제곱하면 형변환됨. 
loss

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25.], dtype=float32)>

In [13]:
loss=tf.reduce_mean(tf.math.square(hypothesis-y_data)) #np로 쓰면 형변환됨
loss

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

In [14]:
with tf.GradientTape() as tape:   #편미분을 구하기 위해서
    hypothesis=x_data*w+b
    loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))

In [15]:
w_grad,b_grad=tape.gradient(loss,[w,b]) #타겟은 loss, 소스는 w,b

In [16]:
w_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-22.], dtype=float32)>

In [17]:
b_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-6.], dtype=float32)>

In [18]:
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [19]:
w-learning_rate*w_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.22], dtype=float32)>

In [20]:
b-learning_rate*b_grad

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.06], dtype=float32)>

In [21]:
for i in range(100):
    with tf.GradientTape() as tape:
        hypothesis=x_data*w+b
        loss=tf.reduce_mean(tf.math.square(hypothesis-y_data))
    
    w_grad,b_grad=tape.gradient(loss,[w,b])

    w.assign_sub(learning_rate*w_grad)
    b.assign_sub(learning_rate*b_grad)

    print('{} {}'.format(i,loss))

0 11.0
1 6.415200233459473
2 3.7433724403381348
3 2.1863298416137695
4 1.2789298295974731
5 0.7501095533370972
6 0.4419064521789551
7 0.2622687816619873
8 0.15755288302898407
9 0.09649773687124252
10 0.06088622659444809
11 0.04010222852230072
12 0.02795911207795143
13 0.02085178717970848
14 0.01667916774749756
15 0.014217016287147999
16 0.012751864269375801
17 0.011867886409163475
18 0.01132277399301529
19 0.010975385084748268
20 0.01074336189776659
21 0.010578843764960766
22 0.01045382209122181
23 0.010351987555623055
24 0.010263906791806221
25 0.010184012353420258
26 0.0101090669631958
27 0.010037219151854515
28 0.00996738113462925
29 0.009898865595459938
30 0.009831316769123077
31 0.009764542803168297
32 0.009698384441435337
33 0.009632790461182594
34 0.00956766214221716
35 0.00950303953140974
36 0.009438863955438137
37 0.00937511958181858
38 0.009311823174357414
39 0.009248954243957996
40 0.009186511859297752
41 0.009124518372118473
42 0.009062910452485085
43 0.009001738391816616
4

In [22]:
w

<tf.Variable 'weight:0' shape=(1,) dtype=float32, numpy=array([0.9492163], dtype=float32)>

In [23]:
b

<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.18334521], dtype=float32)>

In [24]:
y_data

array([1., 2., 3., 4., 5.], dtype=float32)

In [25]:
x_data*w+b

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.1325616, 2.0817778, 3.0309942, 3.9802105, 4.9294267],
      dtype=float32)>

In [26]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1)) #초기값이랑 learn rate가 디폴트로 다른게 들어있어서 우리가 했던거랑 차이가 있음. 그럼 hypothesis는???도 똑같은가?

In [27]:
model.compile(optimizer='SGD',loss='mse')

In [31]:
model.fit(x_data,y_data,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 14ms/step - loss: 0.0252
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0166
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.0116
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0086
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0069
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0059
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0053
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0049
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0047
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0045
Epoch 11/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0044
Epoch 12/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0044
Epoch 13/100
1/1 [==============================] - 0s 5ms/s

In [32]:
model.get_weights()

[array([[0.96842057]], dtype=float32), array([0.1140117], dtype=float32)]

In [33]:
model.predict(x_data)

array([[1.0824323],
       [2.0508528],
       [3.0192735],
       [3.987694 ],
       [4.956115 ]], dtype=float32)

##Subclassing

In [63]:
class Model(tf.keras.layers.Layer):
    def __init__(self):
        super(Model,self).__init__()

        self.w=self.add_weight(shape=(1,1),initializer='random_normal')
        self.b=self.add_weight(shape=(1,),initializer='zeros')

    def call(self,inputs):
        return inputs*self.w+self.b


In [64]:
loss=tf.keras.losses.MeanSquaredError()

In [65]:
def grad(model,inputs,targets):
    with tf.GradientTape() as tape:
        loss_value=loss(targets,model(inputs))

    return tape.gradient(loss_value,[model.w,model.b])

In [66]:
model=Model()

In [67]:
model.w

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.06236804]], dtype=float32)>

In [68]:
model.w

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.06236804]], dtype=float32)>

In [69]:
model([10,20,30])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.62368035, 1.2473607 , 1.871041  ]], dtype=float32)>

In [70]:
optimizer=tf.keras.optimizers.SGD()

In [71]:
for i in range(100):
    grads=grad(model,x_data,y_data)
    optimizer.apply_gradients(zip(grads,[model.w,model.b]))

    print('{} {}'.format(i,loss(y_data,model(x_data))))

0 5.639946937561035
1 3.290999174118042
2 1.9221198558807373
3 1.1243759393692017
4 0.6594613194465637
5 0.38850367069244385
6 0.23057448863983154
7 0.13851308822631836
8 0.08483636379241943
9 0.053528375923633575
10 0.03525608777999878
11 0.024580415338277817
12 0.01833195611834526
13 0.014663586392998695
14 0.012498953379690647
15 0.0112108513712883
16 0.010433698073029518
17 0.009954474866390228
18 0.009649045765399933
19 0.00944509357213974
20 0.009300431236624718
21 0.009190494194626808
22 0.009100988507270813
23 0.009023543447256088
24 0.008953297510743141
25 0.00888743158429861
26 0.008824263699352741
27 0.008762857876718044
28 0.008702616207301617
29 0.008643257431685925
30 0.00858452171087265
31 0.008526371791958809
32 0.008468687534332275
33 0.008411438204348087
34 0.008354619145393372
35 0.008298223838210106
36 0.008242161944508553
37 0.00818652380257845
38 0.008131250739097595
39 0.008076363243162632
40 0.008021846413612366
41 0.007967685349285603
42 0.007913900539278984
43