<a href="https://colab.research.google.com/github/cchio74/forgemaster/blob/master/lab11_linear_regression2_LHC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import tensorflow as tf
import numpy as np

#DATA

In [44]:
x_data=np.array([1,2,3,4,5],np.float32)
y_data=np.array([1,2,3,4,5],np.float32)

#Linear regression

In [45]:
learning_rate=1e-2

In [46]:
w=tf.Variable([0],dtype='float32')
b=tf.Variable([0],dtype='float32')  #앞으로 구해놓을 인자를 미리 정해 놓음

In [47]:
for i in range(100):
    #loss
    with tf.GradientTape() as tape:
        hypothesis=x_data*w+b
        loss=tf.reduce_mean(tf.square(hypothesis-y_data))

    #gradient
    w_grad,b_grad=tape.gradient(loss,[w,b])

    #update
    w.assign_sub(learning_rate*w_grad)
    b.assign_sub(learning_rate*b_grad)

    #display
    if i%10==0:   #10번에 한번씩만 보여줘!
        print('iteration{} loass{}'.format(i,loss))

iteration0 loass11.0
iteration10 loass0.06088622659444809
iteration20 loass0.01074336189776659
iteration30 loass0.009831316769123077
iteration40 loass0.009186511859297752
iteration50 loass0.008584880270063877
iteration60 loass0.008022652938961983
iteration70 loass0.007497233804315329
iteration80 loass0.0070062438026070595
iteration90 loass0.006547394208610058


In [48]:
w.numpy()

array([0.9492163], dtype=float32)

In [49]:
b.numpy()

array([0.18334521], dtype=float32)

In [50]:
x_data*w+b

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.1325616, 2.0817778, 3.0309942, 3.9802105, 4.9294267],
      dtype=float32)>

In [51]:
y_data

array([1., 2., 3., 4., 5.], dtype=float32)

#subclassing

In [52]:
# model
class Model(tf.keras.layers.Layer):
    def __init__(self):
        super(Model,self).__init__()

        self.w=self.add_weight(shape=(1,1))
        self.b=self.add_weight(shape=(1,))

    def call(self,inputs):
        return input*self.w+self.b

In [53]:
# loss
loss=tf.keras.losses.MeanSquaredError()

In [54]:
# Gradient
def grad(model,inputs,targets):
    with tf.GradientTape() as Tape:
        loss_value=loss(targets,model(inputs))
    return tape.gradient(loss_value,[model.w,model.b])

In [55]:
# define
model=Model()
optimizer=tf.keras.optimizers.SGD(learning_rate)

In [56]:
# learning
for i in range(100):
    #gradient
    grads=grad(model,x_data,y_data)

    #update
    optimizer.apply_gradients(zip(grads,[model.w,model.b]))

    #display
    if i%10==0:
        print('{} {}',format(i,loss(y_data,model(x_data))))

ValueError: ignored

#Sequential model

In [61]:
#model
model=tf.keras.Sequential()
model.add(tf.keras.input(shape=(1,)))
model.add(tf.keras.layers.Dense(1,))

model.summary()
tf.keras.utils.plot_model(model,show_shapes=Ture)

AttributeError: ignored

In [58]:
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate),
              loss=tf.keras.losses.MeanSquaredError())

In [62]:
# learning
model.fit(x_data,y_data,epochs=100,verbose=0)

RuntimeError: ignored

In [63]:
model.evoluate(x_data,y_data,verbose=1)

AttributeError: ignored